### ISSUE TITLE
Build failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by PifuYangPeter** [nokia/memory-profiler#15]
It has some error when i build on ubuntu 16.04
- Code version is 0.1.0

- Errors when build memory-profiler:

> error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/yangz/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-0.2.2/src/lib.rs:15:1
   |
15 | #![feature(asm)]
   | ^^^^^^^^^^^^^^^^
>
> error: aborting due to previous error
>
>For more information about this error, try `rustc --explain E0554`.
error: Could not compile `sc`.
warning: build failed, waiting for other jobs to finish...
error: build failed

- Errors when build memory-profiler-cli:
> error: failed to run custom build command for `server-core v0.1.0 (/mnt/e/temp/nokia-memory-profiler/memory-profiler-0.1.0/server-core)`
process didn't exit successfully: `/mnt/e/temp/nokia-memory-profiler/memory-profiler-0.1.0/target/release/build/server-core-eaaa58d183d73b7b/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'cannot launch a child process to install the dependencies for the WebUI: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
error: build failed
`

- system info
> Ubuntu 16.04 LTS  
> Linux XXX 4.5.1-040501-generic #201604121331 SMP Tue Apr 12 17:33:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by koute** [comment]
1. You need to compile it with Rust nightly; stable is currently not supported.
2. You need to have the [Yarn](https://yarnpkg.com/en/) package manager installed to compile the CLI.
